/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Newsletter = {
  _id: string;
  _type: "newsletter";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  createdAt?: string;
};

export type HomeBanner = {
  _id: string;
  _type: "homeBanner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subtitle?: string;
  ctaText?: string;
  ctaLink?: string;
  mediaType?: "image" | "video";
  bannerImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bannerVideo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    _type: "file";
  };
  autoPlay?: boolean;
  showAnimation?: boolean;
  ownerName?: string;
};

export type PlantBreed = {
  _id: string;
  _type: "plantBreed";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  plantName?: string;
  breedName?: string;
  seedUsed?: string;
  varietyType?: "hybrid" | "f1" | "desi";
  description?: string;
  createdBy?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
};

export type FertilizerFormula = {
  _id: string;
  _type: "fertilizerFormula";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  formulaName?: string;
  npk?: string;
  fertilizerForm?: "granular" | "liquid" | "powder";
  releaseType?: "quick" | "slow";
  isOrganic?: boolean;
  description?: string;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
  _key: string;
}>;

export type Address = {
  _id: string;
  _type: "address";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  address?: string;
  city?: string;
  state?: string;
  pinCode?: string;
  default?: boolean;
  createdAt?: string;
};

export type Blogcategory = {
  _id: string;
  _type: "blogcategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  promotionType?: "image" | "video";
  promoImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  promoVideo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    _type: "file";
  };
  videoPoster?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  mediaType?: "image" | "video";
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogVideo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    _type: "file";
  };
  videoPoster?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "blogcategory";
  }>;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  razorpayOrderId?: string;
  razorpayPaymentId?: string;
  razorpaySignature?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  products?: Array<{
    product?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "product";
    };
    quantity?: number;
    sellingUnit?: string;
    otherSellingUnit?: string;
    unitsPerSell?: number;
    priceAtPurchase?: number;
    _key: string;
  }>;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  address?: {
    state?: string;
    pinCode?: string;
    city?: string;
    address?: string;
    name?: string;
  };
  status?: "pending" | "processing" | "paid" | "shipped" | "out_for_delivery" | "delivered" | "cancelled";
  orderDate?: string;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  productVariant?: "plants" | "seeds" | "fertilizer" | "pesticide" | "herbicide" | "fungicide" | "machinery" | "parts" | "tools" | "irrigation" | "feed" | "vet" | "media" | "gear";
  slug?: Slug;
  nursery?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "nursery";
  };
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  price?: number;
  discount?: number;
  stock?: number;
  unit?: string;
  sellingUnit?: "piece" | "kg" | "g" | "liter" | "ml" | "tray" | "pack" | "bag" | "other";
  otherSellingUnit?: string;
  unitsPerSell?: number;
  allowFractional?: boolean;
  shortDescription?: string;
  detailedDescription?: BlockContent;
  whatsappNumber?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  youtubeVideoUrl?: string;
  shippingWeight?: number;
  dimensions?: {
    length?: number;
    width?: number;
    height?: number;
  };
  isFragile?: boolean;
  requiresRefrigeration?: boolean;
  relatedProducts?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "product";
  }>;
  compatibleParts?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "product";
  }>;
  seedType?: "Hybrid" | "Open-Pollinated" | "Heirloom" | "GMO";
  cropType?: "Vegetable" | "Fruit" | "Cereal" | "Flower" | "Fodder" | "Spices";
  germinationRate?: number;
  purity?: number;
  seedTreatment?: string;
  sowingSeason?: Array<string>;
  timeToHarvest?: string;
  diseaseResistance?: Array<string>;
  fertilizerForm?: "Liquid" | "Granular" | "Powder" | "Stick" | "Water-Soluble";
  nutrientComposition?: string;
  micronutrients?: Array<string>;
  applicationMethod?: Array<string>;
  releaseType?: "Slow-Release" | "Quick-Release" | "Controlled-Release";
  isOrganic?: boolean;
  certificationBody?: string;
  chemicalName?: string;
  targetPestsOrWeeds?: Array<string>;
  modeOfAction?: "Systemic" | "Contact" | "Translaminar" | "Stomach";
  dilutionRatio?: string;
  waitingPeriod?: string;
  toxicityClass?: "Class I (Red)" | "Class II (Yellow)" | "Class III (Blue)" | "Class IV (Green)";
  safetyDataSheet?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    _type: "file";
  };
  powerSource?: "Diesel" | "Electric (Battery)" | "Petrol" | "Manual" | "PTO Driven";
  horsepower?: number;
  engineSpecs?: string;
  warrantyInfo?: string;
  afterSalesService?: boolean;
  material?: string;
  partNumber?: string;
  compatibleWith?: string;
  irrigationType?: "Drip System" | "Sprinkler System" | "Pipes" | "Fittings" | "Valves" | "Filter";
  pipeDiameter?: string;
  flowRate?: string;
  animalType?: Array<string>;
  feedType?: "Starter" | "Grower" | "Finisher" | "Concentrate" | "Mineral Mixture";
  nutritionalAnalysis?: BlockContent;
  dosage?: string;
  storageInstructions?: string;
  prescriptionRequired?: boolean;
  reviewCount?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Nursery = {
  _id: string;
  _type: "nursery";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  rating?: number;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  address?: string;
  mapEmbedUrl?: string;
  phoneNumber?: string;
  email?: string;
  website?: string;
  openingHours?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  range?: number;
  featured?: boolean;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | Geopoint | Newsletter | HomeBanner | PlantBreed | FertilizerFormula | BlockContent | Address | Blogcategory | Blog | Author | Order | Product | SanityFileAsset | Nursery | Category | SanityImageCrop | SanityImageHotspot | SanityImageAsset | SanityAssetSourceData | SanityImageMetadata | Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/queries/query.ts
// Variable: NURSERY_QUERY
// Query: *[_type=='nursery'] | order(name asc)
export type NURSERY_QUERYResult = Array<{
  _id: string;
  _type: "nursery";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  rating?: number;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  address?: string;
  mapEmbedUrl?: string;
  phoneNumber?: string;
  email?: string;
  website?: string;
  openingHours?: string;
}>;
// Variable: LATEST_BLOG_QUERY
// Query: *[_type == 'blog' && isLatest == true]|order(name asc){      ...,      blogcategories[]->{      title    }    }
export type LATEST_BLOG_QUERYResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  mediaType?: "image" | "video";
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogVideo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    _type: "file";
  };
  videoPoster?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
  }> | null;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
}>;
// Variable: DEAL_PRODUCTS
// Query: *[_type == 'product' && status == 'hot'] | order(name asc){    ...,"categories": categories[]->title  }
export type DEAL_PRODUCTSResult = Array<never>;
// Variable: NURSERY_BY_SLUG_QUERY
// Query: *[_type == "nursery" && slug.current == $slug][0] {    ...,    "products": *[_type == "product" && references(^._id)] | order(name asc) {      _id,      name,      price,      discount,      stock,      "slug": slug.current,      images,      description,      productVariant    }  }
export type NURSERY_BY_SLUG_QUERYResult = {
  _id: string;
  _type: "nursery";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  rating?: number;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  address?: string;
  mapEmbedUrl?: string;
  phoneNumber?: string;
  email?: string;
  website?: string;
  openingHours?: string;
  products: Array<{
    _id: string;
    name: string | null;
    price: number | null;
    discount: number | null;
    stock: number | null;
    slug: string | null;
    images: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }> | null;
    description: null;
    productVariant: "feed" | "fertilizer" | "fungicide" | "gear" | "herbicide" | "irrigation" | "machinery" | "media" | "parts" | "pesticide" | "plants" | "seeds" | "tools" | "vet" | null;
  }>;
} | null;
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && slug.current == $slug][0]{    ...,     nursery->,     categories[]->{title, "slug": slug.current},     relatedProducts[]->{       name,      "slug": slug.current,      images,      price,      discount,      shortDescription    }  }
export type PRODUCT_BY_SLUG_QUERYResult = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  productVariant?: "feed" | "fertilizer" | "fungicide" | "gear" | "herbicide" | "irrigation" | "machinery" | "media" | "parts" | "pesticide" | "plants" | "seeds" | "tools" | "vet";
  slug?: Slug;
  nursery: {
    _id: string;
    _type: "nursery";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    description?: string;
    rating?: number;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    coverImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    gallery?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }>;
    address?: string;
    mapEmbedUrl?: string;
    phoneNumber?: string;
    email?: string;
    website?: string;
    openingHours?: string;
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  price?: number;
  discount?: number;
  stock?: number;
  unit?: string;
  sellingUnit?: "bag" | "g" | "kg" | "liter" | "ml" | "other" | "pack" | "piece" | "tray";
  otherSellingUnit?: string;
  unitsPerSell?: number;
  allowFractional?: boolean;
  shortDescription?: string;
  detailedDescription?: BlockContent;
  whatsappNumber?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  youtubeVideoUrl?: string;
  shippingWeight?: number;
  dimensions?: {
    length?: number;
    width?: number;
    height?: number;
  };
  isFragile?: boolean;
  requiresRefrigeration?: boolean;
  relatedProducts: Array<{
    name: string | null;
    slug: string | null;
    images: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }> | null;
    price: number | null;
    discount: number | null;
    shortDescription: string | null;
  }> | null;
  compatibleParts?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "product";
  }>;
  seedType?: "GMO" | "Heirloom" | "Hybrid" | "Open-Pollinated";
  cropType?: "Cereal" | "Flower" | "Fodder" | "Fruit" | "Spices" | "Vegetable";
  germinationRate?: number;
  purity?: number;
  seedTreatment?: string;
  sowingSeason?: Array<string>;
  timeToHarvest?: string;
  diseaseResistance?: Array<string>;
  fertilizerForm?: "Granular" | "Liquid" | "Powder" | "Stick" | "Water-Soluble";
  nutrientComposition?: string;
  micronutrients?: Array<string>;
  applicationMethod?: Array<string>;
  releaseType?: "Controlled-Release" | "Quick-Release" | "Slow-Release";
  isOrganic?: boolean;
  certificationBody?: string;
  chemicalName?: string;
  targetPestsOrWeeds?: Array<string>;
  modeOfAction?: "Contact" | "Stomach" | "Systemic" | "Translaminar";
  dilutionRatio?: string;
  waitingPeriod?: string;
  toxicityClass?: "Class I (Red)" | "Class II (Yellow)" | "Class III (Blue)" | "Class IV (Green)";
  safetyDataSheet?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    _type: "file";
  };
  powerSource?: "Diesel" | "Electric (Battery)" | "Manual" | "Petrol" | "PTO Driven";
  horsepower?: number;
  engineSpecs?: string;
  warrantyInfo?: string;
  afterSalesService?: boolean;
  material?: string;
  partNumber?: string;
  compatibleWith?: string;
  irrigationType?: "Drip System" | "Filter" | "Fittings" | "Pipes" | "Sprinkler System" | "Valves";
  pipeDiameter?: string;
  flowRate?: string;
  animalType?: Array<string>;
  feedType?: "Concentrate" | "Finisher" | "Grower" | "Mineral Mixture" | "Starter";
  nutritionalAnalysis?: BlockContent;
  dosage?: string;
  storageInstructions?: string;
  prescriptionRequired?: boolean;
  reviewCount?: number;
} | null;
// Variable: NURSERY_QUERY_BY_PRODUCT
// Query: *[_type == "product" && slug.current == $slug]{  "nurseryName": nursery->title }
export type NURSERY_QUERY_BY_PRODUCTResult = Array<{
  nurseryName: string | null;
}>;
// Variable: MY_ORDERS_QUERY
// Query: *[_type == 'order' && clerkUserId == $userId] | order(orderDate desc){    ...,    "products": products[]{      ...,      product->    }  }
export type MY_ORDERS_QUERYResult = Array<{
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  razorpayOrderId?: string;
  razorpayPaymentId?: string;
  razorpaySignature?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  products: Array<{
    product: {
      _id: string;
      _type: "product";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      productVariant?: "feed" | "fertilizer" | "fungicide" | "gear" | "herbicide" | "irrigation" | "machinery" | "media" | "parts" | "pesticide" | "plants" | "seeds" | "tools" | "vet";
      slug?: Slug;
      nursery?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "nursery";
      };
      categories?: Array<{
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: "category";
      }>;
      price?: number;
      discount?: number;
      stock?: number;
      unit?: string;
      sellingUnit?: "bag" | "g" | "kg" | "liter" | "ml" | "other" | "pack" | "piece" | "tray";
      otherSellingUnit?: string;
      unitsPerSell?: number;
      allowFractional?: boolean;
      shortDescription?: string;
      detailedDescription?: BlockContent;
      whatsappNumber?: string;
      images?: Array<{
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }>;
      youtubeVideoUrl?: string;
      shippingWeight?: number;
      dimensions?: {
        length?: number;
        width?: number;
        height?: number;
      };
      isFragile?: boolean;
      requiresRefrigeration?: boolean;
      relatedProducts?: Array<{
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: "product";
      }>;
      compatibleParts?: Array<{
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: "product";
      }>;
      seedType?: "GMO" | "Heirloom" | "Hybrid" | "Open-Pollinated";
      cropType?: "Cereal" | "Flower" | "Fodder" | "Fruit" | "Spices" | "Vegetable";
      germinationRate?: number;
      purity?: number;
      seedTreatment?: string;
      sowingSeason?: Array<string>;
      timeToHarvest?: string;
      diseaseResistance?: Array<string>;
      fertilizerForm?: "Granular" | "Liquid" | "Powder" | "Stick" | "Water-Soluble";
      nutrientComposition?: string;
      micronutrients?: Array<string>;
      applicationMethod?: Array<string>;
      releaseType?: "Controlled-Release" | "Quick-Release" | "Slow-Release";
      isOrganic?: boolean;
      certificationBody?: string;
      chemicalName?: string;
      targetPestsOrWeeds?: Array<string>;
      modeOfAction?: "Contact" | "Stomach" | "Systemic" | "Translaminar";
      dilutionRatio?: string;
      waitingPeriod?: string;
      toxicityClass?: "Class I (Red)" | "Class II (Yellow)" | "Class III (Blue)" | "Class IV (Green)";
      safetyDataSheet?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
        };
        _type: "file";
      };
      powerSource?: "Diesel" | "Electric (Battery)" | "Manual" | "Petrol" | "PTO Driven";
      horsepower?: number;
      engineSpecs?: string;
      warrantyInfo?: string;
      afterSalesService?: boolean;
      material?: string;
      partNumber?: string;
      compatibleWith?: string;
      irrigationType?: "Drip System" | "Filter" | "Fittings" | "Pipes" | "Sprinkler System" | "Valves";
      pipeDiameter?: string;
      flowRate?: string;
      animalType?: Array<string>;
      feedType?: "Concentrate" | "Finisher" | "Grower" | "Mineral Mixture" | "Starter";
      nutritionalAnalysis?: BlockContent;
      dosage?: string;
      storageInstructions?: string;
      prescriptionRequired?: boolean;
      reviewCount?: number;
    } | null;
    quantity?: number;
    sellingUnit?: string;
    otherSellingUnit?: string;
    unitsPerSell?: number;
    priceAtPurchase?: number;
    _key: string;
  }> | null;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  address?: {
    state?: string;
    pinCode?: string;
    city?: string;
    address?: string;
    name?: string;
  };
  status?: "cancelled" | "delivered" | "out_for_delivery" | "paid" | "pending" | "processing" | "shipped";
  orderDate?: string;
}>;
// Variable: GET_ALL_BLOG
// Query: *[_type == 'blog'] | order(publishedAt desc)[0...$quantity]{  ...,        blogcategories[]->{    title}    }
export type GET_ALL_BLOGResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  mediaType?: "image" | "video";
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogVideo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    _type: "file";
  };
  videoPoster?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
  }> | null;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
}>;
// Variable: SINGLE_BLOG_QUERY
// Query: *[_type == "blog" && slug.current == $slug][0]{  ...,     author->{    name,    image,  },  blogcategories[]->{    title,    "slug": slug.current,  },}
export type SINGLE_BLOG_QUERYResult = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author: {
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  mediaType?: "image" | "video";
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogVideo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    _type: "file";
  };
  videoPoster?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
} | null;
// Variable: BLOG_CATEGORIES
// Query: *[_type == "blog"]{      blogcategories[]->{    ...    }  }
export type BLOG_CATEGORIESResult = Array<{
  blogcategories: Array<{
    _id: string;
    _type: "blogcategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    description?: string;
    promotionType?: "image" | "video";
    promoImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    promoVideo?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
      };
      _type: "file";
    };
    videoPoster?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  }> | null;
}>;
// Variable: OTHERS_BLOG_QUERY
// Query: *[  _type == "blog"  && defined(slug.current)  && slug.current != $slug]|order(publishedAt desc)[0...$quantity]{...  publishedAt,  title,  mainImage,  slug,  author->{    name,    image,  },  categories[]->{    title,    "slug": slug.current,  }}
export type OTHERS_BLOG_QUERYResult = Array<{
  title: string | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  slug: Slug | null;
  author: {
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  categories: null;
}>;
// Variable: HOME_BANNER_QUERY
// Query: *[_type == "homeBanner"][0]{    title,    subtitle,    ctaText,    ctaLink,    mediaType,    bannerImage,    bannerVideo{      asset->{        url      }    },    autoPlay,    showAnimation,    ownerName  }
export type HOME_BANNER_QUERYResult = {
  title: string | null;
  subtitle: string | null;
  ctaText: string | null;
  ctaLink: string | null;
  mediaType: "image" | "video" | null;
  bannerImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  bannerVideo: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  autoPlay: boolean | null;
  showAnimation: boolean | null;
  ownerName: string | null;
} | null;
// Variable: VIDEO_BLOG_QUERY
// Query: *[    _type == "blog"    && mediaType == "video"  ] | order(publishedAt desc){    _id,    title,    slug,    publishedAt,    mediaType,    blogVideo{      asset->{        url      }    },    videoPoster,    blogcategories[]->{      title,      "slug": slug.current    }  }
export type VIDEO_BLOG_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  mediaType: "image" | "video" | null;
  blogVideo: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  videoPoster: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  blogcategories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type=='nursery'] | order(name asc) ": NURSERY_QUERYResult;
    " *[_type == 'blog' && isLatest == true]|order(name asc){\n      ...,\n      blogcategories[]->{\n      title\n    }\n    }": LATEST_BLOG_QUERYResult;
    "*[_type == 'product' && status == 'hot'] | order(name asc){\n    ...,\"categories\": categories[]->title\n  }": DEAL_PRODUCTSResult;
    "\n  *[_type == \"nursery\" && slug.current == $slug][0] {\n    ...,\n    \"products\": *[_type == \"product\" && references(^._id)] | order(name asc) {\n      _id,\n      name,\n      price,\n      discount,\n      stock,\n      \"slug\": slug.current,\n      images,\n      description,\n      productVariant\n    }\n  }\n": NURSERY_BY_SLUG_QUERYResult;
    "*[_type == \"product\" && slug.current == $slug][0]{\n    ..., \n    nursery->, \n    categories[]->{title, \"slug\": slug.current}, \n    relatedProducts[]->{ \n      name,\n      \"slug\": slug.current,\n      images,\n      price,\n      discount,\n      shortDescription\n    }\n  }": PRODUCT_BY_SLUG_QUERYResult;
    "*[_type == \"product\" && slug.current == $slug]{\n  \"nurseryName\": nursery->title\n }": NURSERY_QUERY_BY_PRODUCTResult;
    "\n  *[_type == 'order' && clerkUserId == $userId] | order(orderDate desc){\n    ...,\n    \"products\": products[]{\n      ...,\n      product->\n    }\n  }\n": MY_ORDERS_QUERYResult;
    "*[_type == 'blog'] | order(publishedAt desc)[0...$quantity]{\n  ...,  \n      blogcategories[]->{\n    title\n}\n    }\n  ": GET_ALL_BLOGResult;
    "*[_type == \"blog\" && slug.current == $slug][0]{\n  ..., \n    author->{\n    name,\n    image,\n  },\n  blogcategories[]->{\n    title,\n    \"slug\": slug.current,\n  },\n}": SINGLE_BLOG_QUERYResult;
    "*[_type == \"blog\"]{\n      blogcategories[]->{\n    ...\n    }\n  }": BLOG_CATEGORIESResult;
    "*[\n  _type == \"blog\"\n  && defined(slug.current)\n  && slug.current != $slug\n]|order(publishedAt desc)[0...$quantity]{\n...\n  publishedAt,\n  title,\n  mainImage,\n  slug,\n  author->{\n    name,\n    image,\n  },\n  categories[]->{\n    title,\n    \"slug\": slug.current,\n  }\n}": OTHERS_BLOG_QUERYResult;
    "\n  *[_type == \"homeBanner\"][0]{\n    title,\n    subtitle,\n    ctaText,\n    ctaLink,\n    mediaType,\n    bannerImage,\n    bannerVideo{\n      asset->{\n        url\n      }\n    },\n    autoPlay,\n    showAnimation,\n    ownerName\n  }\n": HOME_BANNER_QUERYResult;
    "\n  *[\n    _type == \"blog\"\n    && mediaType == \"video\"\n  ] | order(publishedAt desc){\n    _id,\n    title,\n    slug,\n    publishedAt,\n    mediaType,\n    blogVideo{\n      asset->{\n        url\n      }\n    },\n    videoPoster,\n    blogcategories[]->{\n      title,\n      \"slug\": slug.current\n    }\n  }\n": VIDEO_BLOG_QUERYResult;
  }
}
